language: python
sudo: required
dist: trusty
install: 
   - python setup.py install
   - pip install robotframework-requests
matrix:
  include:
    - python: "3.6"
      env:
        - ROBOTFRAMEWORK=3.0.2
        - ROBOT_OPTIONS=--dotted
        - INTERPRETER=python3
    - python: "pypy3.5"
      env:
        - ROBOTFRAMEWORK=3.0.2
        - ROBOT_OPTIONS=--dotted
        - INTERPRETER=pypy3
    - python: "2.7"
      env:
        - ROBOTFRAMEWORK=2.9.2
        - ROBOT_OPTIONS=--dotted
        - INTERPRETER=python2
    - python: "2.7"
      env:
        - ROBOTFRAMEWORK=2.8.7
        - ROBOT_OPTIONS=
        - INTERPRETER=python2
    - python: "3.3"
      env:
        - ROBOTFRAMEWORK=3.0.2
        - ROBOT_OPTIONS=--dotted
        - INTERPRETER=python3
script:
  - pybot tests/

