language: python
sudo: required
dist: trusty
install: 
   - pip install falcon
   - python setup.py install
   - pip install robotframework-requests
   - pip install -r requirements.txt
matrix:
  include:
    - python: "3.7"
      env:
        - ROBOTFRAMEWORK=3.1.2
        - ROBOT_OPTIONS=--dotted
        - INTERPRETER=python3
script:
  - pybot --exclude=skip tests/
  - pytest --capture=no tests/

