language: python
sudo: required
dist: xenial
before_script:
   - pip install -U pip
install:    
   - python setup.py install
   - pip install robotframework-requests
matrix:
  include:
    - python: "3.7"
      env:
        - ROBOTFRAMEWORK=3.1.2
        - ROBOT_OPTIONS=--dotted
        - INTERPRETER=python3
script:
  - pybot --exclude=skip tests/
  - pytest --capture=no tests/

